name: flappy_dash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_bloc: ^1.12.17
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/
